# Tasks

GET http://localhost:4000/api/v1/storage/providers?debug=true
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ycnR6RWpZcm9XRkpieEhhbVRFcEJKWmlzTUUiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3Mzc0NzY4MzgsImZ2YSI6WzkxLC0xXSwiaWF0IjoxNzM3NDc2Nzc4LCJpc3MiOiJodHRwczovL2dsYWQtcGlyYW5oYS05Ny5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3Mzc0NzY3NjgsInNpZCI6InNlc3NfMnJ3WG4wSGNTcTVVdTREaTdGVU1XU0JsbDZMIiwic3ViIjoidXNlcl8ycnUwNWlqZ1JSRllDdGhtb1BtVUxnc0VPaWwifQ.R5KIioRIfnXkHjqDQtWqzQiFrxd6dhgF0-6z8mGcqkn0o-vkm5vUJqY_TIrlxD3LV8Vmpno1nNAntdwSQ4edaOrK6uxIEAzgNvDhM9ezhX1f2YG1iytgEr8XQapndm-z-CsWT6IbajdCvrsNeBKqax9KReGf1tfU_4lbcrJpT8UuPu7wngLN7SDsfoObIsA9qYO7KnQ1-mzu-8SjxlCb1TPFGYMajRiUknCp8zstHskQjnExWuJCNNuPhN2da5VmK397ZiR0G9T-X0RF1jOXPir18A2xbSde3Whh_DuifxH1Hb92rliWnTu0MxSxx8xPC_HEExQzcHgJBTkpBK4olA