# Storage Providers

# GET http://localhost:4000/api/v1/storage/providers?debug=true
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ycnR6RWpZcm9XRkpieEhhbVRFcEJKWmlzTUUiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3Mzc0ODEzMDUsImZ2YSI6WzE2NiwtMV0sImlhdCI6MTczNzQ4MTI0NSwiaXNzIjoiaHR0cHM6Ly9nbGFkLXBpcmFuaGEtOTcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzM3NDgxMjM1LCJzaWQiOiJzZXNzXzJyd1huMEhjU3E1VXU0RGk3RlVNV1NCbGw2TCIsInN1YiI6InVzZXJfMnJ1MDVpamdSUkZZQ3RobW9QbVVMZ3NFT2lsIn0.ie1BnT6UR5oKQQSIiYaptDUE-3v8gnR1Ht6E_sG2zjWUoNKZoStQIaWU0DhhpnGBIl8THjuALzNB2BNQ5agizn3tw8IJ2aFvJXMXXgT3sXvimFgg17GiuKygJEy68he33vK6erMMHC7uR0Tdju4CrqgEL887CDU1SbiI36dyIWgqsH8w7ydXHHLqqR3hVALG0aSm5wNwaO1c21zxmVRfWlxJBhCiLqIMnPzvd3ePLlBafA7eRoVeyIUpVqRpCBrsILJsVgOBTz-dsMq1nqVGv7Y1wxV6F0EFtNHJ3nfBM5Ojh149xpKG4B7Y3353ep6Ywrp7me7Qer6Tqi9W7vE7xw

# GOOGLE_DRIVE connect

GET http://localhost:4000/api/v1/storage/GOOGLE_DRIVE/connect?debug=true
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ycnR6RWpZcm9XRkpieEhhbVRFcEJKWmlzTUUiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3Mzc0ODEzOTksImZ2YSI6WzE2NywtMV0sImlhdCI6MTczNzQ4MTMzOSwiaXNzIjoiaHR0cHM6Ly9nbGFkLXBpcmFuaGEtOTcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzM3NDgxMzI5LCJzaWQiOiJzZXNzXzJyd1huMEhjU3E1VXU0RGk3RlVNV1NCbGw2TCIsInN1YiI6InVzZXJfMnJ1MDVpamdSUkZZQ3RobW9QbVVMZ3NFT2lsIn0.E3dJ62l4-nN-1_BrkAwfCzBko6m_jC5crbU9zQ7fJ0vGZLiWrXVDNBjeDZaEbhuXKmevHmndzQvndVefTqIE7PMEcpuliY3imLha_EltnsMsfo1_9UoKoQth98KxaB0P3Bxk0ZgVSX-c_1iMLRGA4YwMzv_6W7Rek53bCEy5f3a0fGKplEOw297rryCY37HzfXLNrmQyGTbAOgiFv7jFCNr3Cao_5QSPqmBzpmZFeoOVyZV5QbFK3LE8h6pUc8QdQqi0gpf3nFxY0jGW_plosVJqi2whH1RWkhkjAOlEqyp-iC7jXgPvYSiLoo-novazkzlmDvAV0QR86RTzTQUZuQ
