# Tasks

GET http://localhost:4000/api/v1/auth/me?debug=true
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ycnR6RWpcm9XRkpieEhhbVRFcEJKWmlzTUUiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3Mzc0NzIyNjQsImZ2YSI6WzE1LC0xXSwiaWF0IjoxNzM3NDcyMjA0LCJpc3MiOiJodHRwczovL2dsYWQtcGlyYW5oYS05Ny5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3Mzc0NzIxOTQsInNpZCI6InNlc3NfMnJ3WG4wSGNTcTVVdTREaTdGVU1XU0JsbDZMIiwic3ViIjoidXNlcl8ycnUwNWlqZ1JSRllDdGhtb1BtVUxnc0VPaWwifQ.IXVC0Qcz6lH8qeITG1mhl0GLloHHhSPQnx8P4s89nHSHscAdDC3x92W9y4tbLke6Oak11mB6cU0PpUoLum4_0xZoOwishFOYsdLrYTQ-Ei7bK3G7fwi5Ag5XbVpm3nACMOkE9it3r-f8aqE_2Mh8Cap3ATK0NSW3jQvEGuy3SHlMBhVUkA2-9GykiAr6mvXBDO4utiUponYVl1XaDnyr333aWuZAuEqHLGLVFQHPFMABjzflGPqlVcWdtWtJhMgIssb5x5jbgm1fwM_ouFOwIanD8D66zlVwnDRcchJjK-7rzRsYBlSJLNPy8vQ_EXmwKPxCnrViUG7DQHfHKqfpZw