# Tasks

GET http://localhost:4000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ycnR6RWpZcm9XRkpieEhhbVRFcEJKWmlzTUUiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3Mzc0MTA1NDYsImZ2YSI6WzExLC0xXSwiaWF0IjoxNzM3NDEwNDg2LCJpc3MiOiJodHRwczovL2dsYWQtcGlyYW5oYS05Ny5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3Mzc0MTA0NzYsInNpZCI6InNlc3NfMnJ1WEVWMGJTWHB6MmV6Sk5XbW9ETG1LeHZ5Iiwic3ViIjoidXNlcl8ycnUwNWlqZ1JSRllDdGhtb1BtVUxnc0VPaWwifQ.FzNjBkqs953UV6ynYxoIOi8iw629QHZKslT0PGdfnWKxN3YAMShQMFJFuskFUHjPv_YFfyAuwwV90d5iIDypdmiKsx77X-o3DhCPU-TjlL8HaME0wzcKwEpUIeZffOyl8pYXwULnnZJUVOI7ROaKjYPP5PlAoJcJXk__g3nNi6WMnfb4n1CBlLx3AEran0gaHL7BN1L-kKSaiQ08_aEibd89Jz276udKOyP7z4N0LHpqpVWauZClFcYFQNxuXkKW7Mo5iRf85vJnNmTNVvv5W5SOE9O9gz8xMFS861XbVWhbYdoRivvxirK9yfjjG0c-2o67_KhXiox2vBrSMwrO-Q
